ktor {
    deployment {
        port = 3000
        port = ${?PORT}
    }
    application {
        modules = [ com.shadmin.ApplicationKt.module ]
    }
}

app {
    env = "development"
    env = ${?APP_ENV}

    jwt {
        access-secret = "shadmin-access-secret-key-2024"
        access-secret = ${?ACCESS_TOKEN_SECRET}
        refresh-secret = "shadmin-refresh-secret-key-2024"
        refresh-secret = ${?REFRESH_TOKEN_SECRET}
        access-expiry-minute = 180
        access-expiry-minute = ${?ACCESS_TOKEN_EXPIRY_MINUTE}
        refresh-expiry-minute = 1800
        refresh-expiry-minute = ${?REFRESH_TOKEN_EXPIRY_MINUTE}
    }

    database {
        type = "h2"
        type = ${?DB_TYPE}
        driver = "org.h2.Driver"
        url = "jdbc:h2:file:./data/shadmin;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
        url = ${?DB_URL}
        user = "sa"
        user = ${?DB_USER}
        password = ""
        password = ${?DB_PASSWORD}
    }

    admin {
        username = "admin"
        username = ${?ADMIN_USERNAME}
        password = "shadmin"
        password = ${?ADMIN_PASSWORD}
        email = "admin@gmail.com"
        email = ${?ADMIN_EMAIL}
    }

    security {
        max-login-failures = 5
        lockout-duration-seconds = 300
    }
}
